name: Lighthouse report generation

on:
  push:
    branches: [fix-lighthouse-report-upload-action]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Installing deps"
        run: |
          yarn
          npm i -g @lhci/cli@0.9.x serve

      - name: "Build Prodcution"
        run: yarn build

      - name: "Serve Prodcution Server"
        run: serve -s build &

      - name: "Run Lighthouse tests"
        continue-on-error: true
        run: lhci autorun && ls

      - name: "Upload report"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lhci-reports
          path: |
            .lighthouseci/
          # if-no-files-found: error
          # if: ${{ success() && steps.lighthouse.outputs.hasHtmlReport == 'true' && steps.lighthouse.outputs.hasJsonReport == 'true' }}
